name: publish

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker-registry.online.ntnu.no
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          target: onlineweb4-nginx
          push: true
          tags: docker-registry.online.ntnu.no/onlineweb4-nginx:latest,docker-registry.online.ntnu.no/onlineweb4-nginx:${GITHUB_SHA}
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and push django
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker-registry.online.ntnu.no/onlineweb4:latest,docker-registry.online.ntnu.no/onlineweb4:${GITHUB_SHA}
          cache-from: type=local,src=/tmp/.buildx-cache